app/gradebook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Home View
    url(r'^$', views.HomePageView.as_view(), name='home'),

    # Authentication Views
    url(r'^login/$', views.auth_v.LoginPageView.as_view(), name='login'),
    url(r'^logout/$', views.auth_v.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.auth_v.RegisterPageView.as_view(), name='register'),
    url(r'^register/teacher/$', views.auth_v.RegisterTeacher.as_view(), name='register_teacher'),
    url(r'^register/student/$', views.auth_v.RegisterStudent.as_view(), name='register_student'),
    url(r'^secret/$', views.home_v.SomeSecretView.as_view(), name='secret'),

    # List Views
    url(r'^allteachers/$', views.lists_v.TeacherList.as_view(), name='teacher_list'),
    url(r'^allstudents/$', views.lists_v.StudentList.as_view(), name='student_list'),
    url(r'^allcourses/$', views.lists_v.CourseList.as_view(), name='course_list'),
    url(r'^staff/$', views.lists_v.SectionList.as_view(), name='section_list'),

    # Section View
    url(r'^staff/(?P<sec>\d+)/$', views.sections_v.SpecificSection.as_view(), name='section'),

    # Announcement Views
    url(r'^staff/(?P<sec>\d+)/announcements/add/$', views.announcements_v.AnnouncementCreate.as_view(), name='announcement_new'),
    url(r'^staff/(?P<sec>\d+)/announcements/(?P<pk>\d+)/edit/$', views.announcements_v.AnnouncementUpdate.as_view(), name='announcement_edit'),
    url(r'^staff/(?P<sec>\d+)/announcements/(?P<pk>\d+)/delete/$', views.announcements_v.AnnouncementDelete.as_view(), name='announcement_delete'),

    # Assignment Views
    url(r'^staff/(?P<sec>\d+)/assignments/add/$', views.assignments_v.AssignmentCreate.as_view(), name='assignment_new'),
    url(r'^staff/(?P<sec>\d+)/assignments/(?P<pk>\d+)/edit/$', views.assignments_v.AssignmentUpdate.as_view(), name='assignment_edit'),
    url(r'^staff/(?P<sec>\d+)/assignments/(?P<pk>\d+)/delete/$', views.assignments_v.AssignmentDelete.as_view(), name='assignment_delete'),
    url(r'^staff/(?P<sec>\d+)/assignments/(?P<asn>\d+)/stats/$', views.assignments_v.AssignmentStats.as_view(), name='assignment_stats'),

    # Enrollment Views
    url(r'^staff/(?P<sec>\d+)/enrollments/add/$', views.enrollments_v.EnrollmentCreate.as_view(), name='enrollment_new'),
    url(r'^staff/(?P<sec>\d+)/enrollments/(?P<pk>\d+)/delete/$', views.enrollments_v.EnrollmentDelete.as_view(), name='enrollment_delete'),

    # Grade Views
    url(r'^staff/(?P<sec>\d+)/enrollments/(?P<enr>\d+)/grades/$', views.grades_v.GradeList.as_view(), name='grade_list'),
    url(r'^staff/(?P<sec>\d+)/enrollments/(?P<enr>\d+)/grades/add/$', views.grades_v.GradeCreate.as_view(), name='grade_new'),
    url(r'^staff/(?P<sec>\d+)/enrollments/(?P<enr>\d+)/grades/add/off/(?P<asn>\d+)/$', views.grades_v.GradeCreateOffAssignment.as_view(), name='grade_new_off_assignment'),
    url(r'^staff/(?P<sec>\d+)/enrollments/(?P<enr>\d+)/grades/(?P<pk>\d+)/edit/(?P<asn>\d+)/$', views.grades_v.GradeUpdate.as_view(), name='grade_edit'),
    url(r'^staff/(?P<sec>\d+)/enrollments/(?P<enr>\d+)/grades/(?P<pk>\d+)/delete/$', views.grades_v.GradeDelete.as_view(), name='grade_delete'),
]

app/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('gradebook.urls'))
]

app/gradebook/models.py
from django.db import models
from django.utils import timezone
from .utils import *
import datetime
import pytz


class Course(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    SUBJECTS = {
        ('english', "ENGLISH"),
        ('math', "MATH")
    }

    subject = models.CharField(choices=SUBJECTS, max_length=20)

    def __str__(self):
        return self.title + ": " + self.description


class Person(models.Model):
    user = models.OneToOneField('auth.User')

    def __str__(self):
        return self.user.last_name + ", " + self.user.first_name


class Teacher(Person):
    def __str__(self):
        return "Teacher: " + super().__str__()


class Section(models.Model):
    teacher = models.ForeignKey(Teacher)
    course = models.ForeignKey(Course)

    section_id = models.IntegerField()
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.course.title + ": Section " + str(self.section_id)


class Student(Person):
    student_id = models.IntegerField(primary_key=True)

    def __str__(self):
        return str(self.student_id) + " - " + super().__str__()


class Assignment(models.Model):
    section = models.ForeignKey(Section)

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

    # Separated because materialize.css does not play well with DateTime form fields.
    # date_time_created uses timezone.now, so it's okay for that to stay as it is.
    date_due = models.DateField(default=datetime.date.today)
    time_due = models.TimeField(default=datetime.time)

    points_possible = models.IntegerField()

    CATEGORIES = {
        ('essay', "Essay"),
        ('test', "Test"),
        ('quiz', "Quiz"),
        ('ps', "Problem Set"),
        ('hwk', "Homework"),
        ('ec', "Extra Credit")
    }

    category = models.CharField(choices=CATEGORIES, max_length=20)

    def __str__(self):
        return "[" + self.get_assignment_category() + "] " + str(self.title) + ": " + str(self.description)

    def get_assignment_category(self):
        return dict(self.CATEGORIES).get(str(self.category))


class Enrollment(models.Model):
    section = models.ForeignKey(Section)
    student = models.ForeignKey(Student)

    def __str__(self):
        return str(self.section) + ": " + str(self.student)


class Grade(models.Model):
    enrollment = models.ForeignKey(Enrollment)
    assignment = models.ForeignKey(Assignment)

    ASSIGNMENT_GRADES = (
        ('a+', "A+"), ('a', "A"), ('a-', "A-"),
        ('b+', "B+"), ('b', "B"), ('b-', "B-"),
        ('c+', "C+"), ('c', "C"), ('c-', "C-"),
        ('d+', "D+"), ('d', "D"), ('d-', "D-"),
        ('f', "F")
    )

    points = models.FloatField()
    letter_grade = models.CharField(choices=ASSIGNMENT_GRADES, max_length=3, default="A+")
    date_time_turned_in = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return super().__str__() + str(self.assignment) + " - " + str(self.letter_grade)

    def get_percent_grade(self):
        return to_percent(self.points, self.assignment.points_possible)

    def get_grade(self):
        return dict(self.ASSIGNMENT_GRADES).get(str(self.letter_grade))

    def on_time(self):
        """Multiple function calls when templating, but it's to make everything simpler."""
        naive_assignment_dt_due = datetime.datetime.combine(self.assignment.date_due, self.assignment.time_due)
        local_timezone = pytz.timezone("America/Los_Angeles")
        local_assignment_dt_due = local_timezone.localize(naive_assignment_dt_due, is_dst=None)
        utc_dt = local_assignment_dt_due.astimezone(pytz.utc)
        return self.date_time_turned_in <= utc_dt


class Announcement(models.Model):
    section = models.ForeignKey(Section)
    headline = models.CharField(max_length=50)
    details = models.TextField(max_length=200)
    date_time_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "[{section}] {title}".format(section=self.section, title=self.headline)

app/gradebook/views/announcements_v.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.base import ContextMixin

from gradebook.models import Announcement, Section
from gradebook.views.utils_mixins import SectionIDMixin


class AnnouncementViewMixin(ContextMixin):
    model = Announcement

    def get_success_url(self):
        return reverse_lazy('section', kwargs={'sec': self.kwargs['sec']})


class AnnouncementFormMixin(object):
    fields = ['section', 'headline', 'details', 'date_time_created']

    def get_initial(self):
        section = get_object_or_404(Section, pk=self.kwargs['sec'])
        return {'section': section}


class AnnouncementCreate(LoginRequiredMixin, AnnouncementViewMixin, AnnouncementFormMixin, SectionIDMixin, CreateView):
    def get_form(self, form_class=None):
        form = super(AnnouncementCreate, self).get_form(form_class)
        form.fields['section'].queryset = Section.objects.filter(pk=self.kwargs['sec'])
        return form

    def get_context_data(self, **kwargs):
        context = super(AnnouncementCreate, self).get_context_data(**kwargs)
        context['title'] = "Create an assignment"
        return context


class AnnouncementUpdate(LoginRequiredMixin, AnnouncementViewMixin, AnnouncementFormMixin, SectionIDMixin, UpdateView):
    def get_form(self, form_class=None):
        form = super(AnnouncementUpdate, self).get_form(form_class)
        form.fields['section'].queryset = Section.objects.filter(pk=self.kwargs['sec'])
        return form

    def get_context_data(self, **kwargs):
        context = super(AnnouncementUpdate, self).get_context_data(**kwargs)
        announcement = get_object_or_404(Announcement, pk=self.kwargs['pk'])
        context['title'] = "Editing announcement {announcement}".format(announcement=announcement)
        return context


class AnnouncementDelete(LoginRequiredMixin, AnnouncementViewMixin, DeleteView):
    pass

app/gradebook/views/assignments_v.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.db.models import Max
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, UpdateView, TemplateView

from gradebook.models import Assignment, Grade, Enrollment, Section
from gradebook.views.utils_mixins import SectionIDMixin
from gradebook.utils import *


class AssignmentViewMixin(object):
    model = Assignment

    def get_success_url(self):
        return reverse_lazy('section', kwargs={'sec': self.kwargs['sec']})


class AssignmentFormMixin(object):
    fields = ['section', 'title', 'description', 'category', 'points_possible', 'date_due', 'time_due']


class AssignmentCreate(LoginRequiredMixin, AssignmentViewMixin, AssignmentFormMixin, SectionIDMixin, CreateView):
    def get_form(self, form_class=None):
        form = super(AssignmentCreate, self).get_form(form_class)
        form.fields['section'].queryset = Section.objects.filter(pk=self.kwargs['sec'])
        return form

    def get_initial(self):
        section = get_object_or_404(Section, pk=self.kwargs['sec'])
        return {'section': section}

    def get_context_data(self, **kwargs):
        context = super(AssignmentCreate, self).get_context_data(**kwargs)
        context['title'] = "Create a new assignment"
        return context


class AssignmentUpdate(LoginRequiredMixin, AssignmentViewMixin, AssignmentFormMixin, SectionIDMixin, UpdateView):
    def get_form(self, form_class=None):
        form = super(AssignmentUpdate, self).get_form(form_class)
        form.fields['section'].queryset = Section.objects.filter(pk=self.kwargs['sec'])
        return form

    def get_context_data(self, **kwargs):
        context = super(AssignmentUpdate, self).get_context_data(**kwargs)
        assignment = get_object_or_404(Assignment, pk=self.kwargs['pk'])
        context['title'] = "Editing: {assignment}".format(assignment=assignment)
        return context


class AssignmentDelete(LoginRequiredMixin, AssignmentViewMixin, DeleteView):
    pass  # TODO;


class AssignmentStats(LoginRequiredMixin, SectionIDMixin, TemplateView):
    template_name = 'gradebook/assignment_stats.html'

    def get_context_data(self, **kwargs):
        context = super(AssignmentStats, self).get_context_data(**kwargs)
        section = get_object_or_404(Section, pk=self.kwargs['sec'])
        assignment = get_object_or_404(Assignment, pk=self.kwargs['asn'])
        grades = Grade.objects.filter(assignment=assignment)
        enrollments = Enrollment.objects.filter(section=section)

        context['current_section'] = section
        context['assignment'] = assignment
        grades = grades.order_by('-points') # Sort from highest points to lowest.
        context['assignment_summary'] = {
            'A+': 0, 'A': 0, 'A-': 0,
            'B+': 0, 'B': 0, 'B-': 0,
            'C+': 0, 'C': 0, 'C-': 0,
            'D+': 0, 'D': 0, 'D-': 0,
            'F': 0, 'N': 0
        }

        context['grades_with_colors'] = []
        # The sum of points earned and possible for all students.
        # This is used to determine the average grade.
        points_earned_btw_all_students = 0.0
        points_possible_btw_all_students = 0
        num_of_late_assignments = 0

        for grade in grades:
            context['assignment_summary'][grade.letter_grade.upper()] += 1
            points_earned_btw_all_students += grade.points
            points_possible_btw_all_students += assignment.points_possible
            if not(grade.on_time()):
                num_of_late_assignments += 1

            # grade logic
            color = ""
            grade_of_current = grade.get_grade()[0:1]
            if grade_of_current == "A":
                color = "#a5d6a7"
            elif grade_of_current == "B":
                color ="#b3e5fc"
            elif grade_of_current == "C":
                color = "#f0f4c3"
            else:
                color = "#ffcdd2"
            context['grades_with_colors'].append((grade, color))

        context['average_grade'] = to_percent(
            points_earned_btw_all_students,
            points_possible_btw_all_students
        ) if points_possible_btw_all_students != 0 else 'N'

        # [N] is the number of non-graded assignments.
        context['assignment_summary']['N'] = len(enrollments) - sum(context['assignment_summary'].values())
        max_points = grades.aggregate(Max('points'))['points__max'] if len(grades) != 0 else 0
        context['highest_grade'] = to_percent(
            max_points,
            assignment.points_possible
        ) if points_possible_btw_all_students != 0 else 'N'
        context['num_of_late_assignments'] = num_of_late_assignments

        enrollments_graded = [grade.enrollment for grade in grades]

        context['enrollments_to_be_graded'] = [
            enrollment for enrollment in enrollments if enrollment not in enrollments_graded
            ]

        return context

app/gradebook/views/enrollments_v.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView

from gradebook.models import Enrollment, Section, Student
from gradebook.views.utils_mixins import SectionIDMixin


class EnrollmentViewMixin(object):
    model = Enrollment

    def get_success_url(self):
        return reverse_lazy('section', kwargs={'sec': self.kwargs['sec']})


class EnrollmentCreate(LoginRequiredMixin, EnrollmentViewMixin, SectionIDMixin, CreateView):
    fields = ['section', 'student']

    def get_form(self, form_class=None):
        """
        Only displays the section to prevent enrolling to other sections.
        Only displays students not already enrolled to be in the queryset.
        """
        form = super(EnrollmentCreate, self).get_form(form_class)
        students = Student.objects.all()
        pks_of_students_not_enrolled = []
        for student in students:
            enrollment = Enrollment.objects.filter(student=student, section=self.kwargs['sec']).first()
            if enrollment is None:
                pks_of_students_not_enrolled.append(student.pk)

        form.fields['section'].queryset = Section.objects.filter(pk=self.kwargs['sec'])
        form.fields['student'].queryset = Student.objects.filter(pk__in=pks_of_students_not_enrolled)

        return form

    def get_initial(self):
        section = get_object_or_404(Section, pk=self.kwargs['sec'])
        return {'section': section}

    def get_context_data(self, **kwargs):
        context = super(EnrollmentCreate, self).get_context_data(**kwargs)
        context['title'] = "Enroll a new student"
        return context


class EnrollmentDelete(LoginRequiredMixin, EnrollmentViewMixin, DeleteView):
    pass

app/gradebook/views/home_v.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView

from gradebook.models import Student, Teacher


class HomePageView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            url = ''
            try:
                teacher = Teacher.objects.filter(user=request.user)
                if teacher is not None:
                    url = 'section_list'
            except Teacher.DoesNotExist:  # Not sure how to do exceptions properly yet.
                raise ObjectDoesNotExist
            try:
                student = Student.objects.filter(user=request.user)
                if student is not None:
                    url = 'secret'
            except:
                raise ObjectDoesNotExist
            return redirect(url)
        return super(HomePageView, self).dispatch(request, *args, **kwargs)


class SomeSecretView(LoginRequiredMixin, TemplateView):
    template_name = 'gradebook/secret.html'
    login_url = '/login/'
    raise_exception = False

app/gradebook/templates/base_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ title }}</title>

  {% load staticfiles %}

  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/materialize.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/auth_pages.css' %}"/>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

<div class="container">
  <h3>{{ title }}</h3>
  <table class="highlight">
    {% block content %}
    {% endblock %}
  </table>
</div>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</body>
</html>

app/gradebook/templates/generic_view.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Gradebook</title>
  {% load staticfiles %}

  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/materialize.css' %}"/>

  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/portal.css' %}"/>

  <script src="https://use.fontawesome.com/a80d9ff4a0.js"></script>

  <!-- Load d3.js and c3.js -->
  <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <script src="{% static 'gradebook/c3/c3.min.js' %}"></script>
  <link href="{% static 'gradebook/c3/c3.css' %}" rel="stylesheet" type="text/css">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>
<body>
<div class="container">
  <nav>
    <div class="nav-wrapper">
      <a href="{% url 'section_list' %}" class="brand-logo" style="padding-left: 5px;">
        {{ request.user.last_name }}, {{ request.user.first_name }} [{{ request.user }}]
      </a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'section_list' %}">Sections</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="{% url 'section_list' %}">Sections</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="{% static 'gradebook/js/materialize.js' %}"></script>
<script type="text/javascript"> // This loads on every single page. Kinda a waste, but it's fine for this simple project.
$(document).ready(function () {
  $(".button-collapse").sideNav();
  $('select').material_select();
  $("#id_date_time_created, #id_date_due").pickadate({
    format: 'yyyy-mm-dd',
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
//    document.getElementById('id_date_created').value.length += "22:53:05"
});
</script>
</body>
</html>

app/gradebook/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/materialize.css' %}"/>
</head>
<body>
<div id="container" class="center-align">
<h1>Welcome to Grader</h1>

<a class="waves-effect waves-light btn-large" href="{% url 'login' %}">Login</a>
<a class="waves-effect waves-light btn-large" href="{% url 'register' %}">Register</a>
</div>
<script type="text/javascript" src="{% static 'gradebook/js/materialize.js' %}"></script>
</body>
</html>

app/gradebook/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  {% load staticfiles %}

  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/materialize.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'gradebook/css/auth_pages.css' %}"/>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

<div id="container" style="margin: 0 auto;">
  <div class="row">
    <form class="col s8 m6 offset-m4" method="POST">
      <div class="row">
        <div class="col s8"><h3 class="header">Grader Portal</h3></div>
      </div>
      <div class="row">
        <div class="col s6">
          {{ form.username.errors }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s8">
          {{ form.username }}
          <label for="username">Username</label>
        </div>
      </div>
      {% if form.password.errors %}
      <div class="row">
        <div class="col s6">
          {{ form.password.errors }}
        </div>
      </div>
      {% endif %}
      <div class="row">
        <div class="input-field col s8">
          {{ form.password }}
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s4">
          <button class="btn waves-effect waves-light btn" type="submit" name="action">
            Submit
            <i class="material-icons right">send</i>
          </button>
        </div>
      </div>
    </form>
  </div>

</div>

<!-- scripts -->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
<!-- end scripts -->

</body>
</html>

app/gradebook/templates/student_list.html
{% extends 'base_list.html' %}

{% block content %}

<thead>
<tr>
  <th data-field="student_id">Student ID</th>
  <th data-field="last_name">Last Name</th>
  <th data-field="first_name">First Name</th>
  <th data-field="email">Email</th>
</tr>
</thead>

<tbody>
{% for student in student_list %}
<tr>
  <td>{{ student.student_id }}</td>
  <td>{{ student.user.last_name }}</td>
  <td>{{ student.user.first_name }}</td>
  <td>{{ student.user.email }}</td>
</tr>
{% endfor %}
</tbody>

{% endblock %}

app/gradebook/templates/teacher_list.html
{% extends 'base_list.html' %}

{% block content %}

<thead>
<tr>
  <th data-field="first_name">First Name</th>
  <th data-field="last_name">Last Name</th>
  <th data-field="email">Email</th>
</tr>
</thead>

<tbody>
{% for teacher in teacher_list %}
<tr>
  <td>{{ teacher.user.first_name }}</td>
  <td>{{ teacher.user.last_name }}</td>
  <td>{{ teacher.user.email }}</td>
</tr>
{% endfor %}
</tbody>

{% endblock %}